version: '3'

services:
  client:
    restart: always
    build: ./client
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3000:3000
  server:
    restart: always
    build: ./server
    environment:
     - NODE_ENV="production"
    ports:
      - 3001:3001